version: '3'

services:
 db:
  image: "mysql:5.6"
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: dbname
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
    #PYTHONUSERBASE: ~/.virtualens/djangodev
 web:
  build: .
  command: /bin/sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
  volumes:
   - .:/code
  ports:
   - "8000:8000"
  links:
   - db
  depends_on:
   - db

