version: '3'

services:
 db:
  image: "mysql:5.6"
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: dbname
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
    #PYTHONUSERBASE: ~/.virtualens/djangodev
 web:
  build: .
  command: /bin/sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 && mariadb --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  volumes:
   - .:/code
  ports:
   - "8000:8000"
  links:
   - db
  depends_on:
   - db

