# Generated by Django 2.1.dev20171103140946 on 2017-11-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlodeji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
